function outputs = analyze_noise_robustness(csvFile, outputDir)
% analyze_noise_robustness
% -------------------------------------------------------------------------
% noise-model robustness analysis for the -5 dB experiment.
%
% INPUT
%   csvFile   : noise_robustness_results.csv generated by PACT v9.3
%   outputDir : output folder
%
% OUTPUTS
%   noise_robustness_phantom_level.csv
%   noise_robustness_absolute_summary.csv
%   noise_robustness_crossover_summary.csv
%   Figure_noise_model_robustness.png
%   Figure_noise_model_robustness.pdf
%
% STATISTICAL UNIT
%   Noise realizations are first averaged within each phantom. The figure
%   then displays the three phantom-level values explicitly. Because the
%   reviewer-driven stress test contains only three phantoms, this script
%   intentionally avoids formal p-values and narrow asymptotic confidence
%   intervals. Mean and min-max ranges are shown descriptively.
%
% MAIN QUESTION
%   Does the full-view -5 dB SSIM crossover of DMAS / DASDSF relative to
%   DAS persist under non-IID Gaussian noise?
% -------------------------------------------------------------------------

if nargin < 1 || isempty(csvFile)
    csvFile = fullfile(pwd,'benchmark_v93_reviewer_revision', ...
        'noise_robustness_results.csv');
end
if nargin < 2 || isempty(outputDir)
    outputDir = fullfile(fileparts(csvFile),'NOISE_ROBUSTNESS_REVISION');
end
if ~isfolder(outputDir)
    mkdir(outputDir);
end
if ~isfile(csvFile)
    error('PACT:MissingNoiseRobustnessCSV', ...
        ['Could not find:\n%s\n\nDo NOT rerun the full benchmark yet. ' ...
         'First check whether noise_robustness_results.csv exists in ' ...
         'benchmark_v93_reviewer_revision.'], csvFile);
end

T = readtable(csvFile, 'TextType','string');

required = ["Phantom","NoiseModel","SensorGeometry","Algorithm", ...
    "NoiseRealization","PSNR_ROI_dB","SSIM","Dice"];
missing = required(~ismember(required,string(T.Properties.VariableNames)));
if ~isempty(missing)
    error('PACT:MissingColumns','Missing required columns: %s', ...
        strjoin(missing,', '));
end

% Canonical labels/order.
noiseOrder = ["IID_GAUSSIAN","CHANNEL_CORRELATED_GAUSSIAN", ...
              "HETEROSCEDASTIC_GAUSSIAN","LAPLACE_IID"];
noiseLabels = ["IID Gaussian","Channel-correlated","Heteroscedastic","Laplace IID"];
geomOrder = ["CIRCULAR_FULL","LIMITED_VIEW_ARC"];
geomLabels = ["Full view","Limited view"];
focusMethods = ["DAS","DMAS","DASDSF"];

% Restrict the crossover analysis to the methods directly implicated in the
% reviewer comment. The raw CSV is preserved and can still be used for the
% other methods.
Tf = T(ismember(T.NoiseModel,noiseOrder) & ...
       ismember(T.SensorGeometry,geomOrder) & ...
       ismember(T.Algorithm,focusMethods),:);

if isempty(Tf)
    error('PACT:NoMatchingRows','No expected noise-robustness rows were found.');
end

%% Phantom-level aggregation: average realizations FIRST
phantoms = unique(Tf.Phantom,'stable');
rows = cell(0,9);

for p = 1:numel(phantoms)
    for n = 1:numel(noiseOrder)
        for g = 1:numel(geomOrder)
            for m = 1:numel(focusMethods)
                idx = Tf.Phantom==phantoms(p) & ...
                      Tf.NoiseModel==noiseOrder(n) & ...
                      Tf.SensorGeometry==geomOrder(g) & ...
                      Tf.Algorithm==focusMethods(m);
                if ~any(idx), continue; end
                rows(end+1,:) = { ...
                    phantoms(p),noiseOrder(n),geomOrder(g),focusMethods(m), ...
                    mean(Tf.PSNR_ROI_dB(idx),'omitnan'), ...
                    mean(Tf.SSIM(idx),'omitnan'), ...
                    mean(Tf.Dice(idx),'omitnan'), ...
                    mean(Tf.HD95_mm(idx),'omitnan'), ...
                    nnz(idx)}; %#ok<AGROW>
            end
        end
    end
end

P = cell2table(rows,'VariableNames', ...
    {'Phantom','NoiseModel','SensorGeometry','Algorithm', ...
     'PSNR_ROI_dB','SSIM','Dice','HD95_mm','NumRealizations'});
P.Phantom = string(P.Phantom);
P.NoiseModel = string(P.NoiseModel);
P.SensorGeometry = string(P.SensorGeometry);
P.Algorithm = string(P.Algorithm);

writetable(P,fullfile(outputDir,'noise_robustness_phantom_level.csv'));

%% Absolute summary across phantom-level means
absRows = cell(0,13);
for n = 1:numel(noiseOrder)
    for g = 1:numel(geomOrder)
        for m = 1:numel(focusMethods)
            idx = P.NoiseModel==noiseOrder(n) & ...
                  P.SensorGeometry==geomOrder(g) & ...
                  P.Algorithm==focusMethods(m);
            if ~any(idx), continue; end
            vP = P.PSNR_ROI_dB(idx);
            vS = P.SSIM(idx);
            vD = P.Dice(idx);
            absRows(end+1,:) = {noiseOrder(n),geomOrder(g),focusMethods(m), ...
                nnz(idx), ...
                mean(vP,'omitnan'),median(vP,'omitnan'),min(vP),max(vP), ...
                mean(vS,'omitnan'),median(vS,'omitnan'),min(vS),max(vS), ...
                mean(vD,'omitnan')}; %#ok<AGROW>
        end
    end
end

A = cell2table(absRows,'VariableNames', ...
    {'NoiseModel','SensorGeometry','Algorithm','NumPhantoms', ...
     'MeanPSNR_dB','MedianPSNR_dB','MinPSNR_dB','MaxPSNR_dB', ...
     'MeanSSIM','MedianSSIM','MinSSIM','MaxSSIM','MeanDice'});
A.NoiseModel = string(A.NoiseModel);
A.SensorGeometry = string(A.SensorGeometry);
A.Algorithm = string(A.Algorithm);
writetable(A,fullfile(outputDir,'noise_robustness_absolute_summary.csv'));

%% Per-phantom deltas against DAS
deltaRows = cell(0,11);
testMethods = ["DMAS","DASDSF"];

for p = 1:numel(phantoms)
    for n = 1:numel(noiseOrder)
        for g = 1:numel(geomOrder)
            baseIdx = P.Phantom==phantoms(p) & ...
                      P.NoiseModel==noiseOrder(n) & ...
                      P.SensorGeometry==geomOrder(g) & ...
                      P.Algorithm=="DAS";
            if nnz(baseIdx)~=1, continue; end
            for m = 1:numel(testMethods)
                idx = P.Phantom==phantoms(p) & ...
                      P.NoiseModel==noiseOrder(n) & ...
                      P.SensorGeometry==geomOrder(g) & ...
                      P.Algorithm==testMethods(m);
                if nnz(idx)~=1, continue; end
                deltaRows(end+1,:) = {phantoms(p),noiseOrder(n),geomOrder(g), ...
                    testMethods(m), ...
                    P.SSIM(idx)-P.SSIM(baseIdx), ...
                    P.PSNR_ROI_dB(idx)-P.PSNR_ROI_dB(baseIdx), ...
                    P.Dice(idx)-P.Dice(baseIdx), ...
                    P.SSIM(idx),P.SSIM(baseIdx), ...
                    P.PSNR_ROI_dB(idx),P.PSNR_ROI_dB(baseIdx)}; %#ok<AGROW>
            end
        end
    end
end

D = cell2table(deltaRows,'VariableNames', ...
    {'Phantom','NoiseModel','SensorGeometry','Algorithm', ...
     'DeltaSSIM_vs_DAS','DeltaPSNR_dB_vs_DAS','DeltaDice_vs_DAS', ...
     'MethodSSIM','DAS_SSIM','MethodPSNR_dB','DAS_PSNR_dB'});
D.Phantom = string(D.Phantom);
D.NoiseModel = string(D.NoiseModel);
D.SensorGeometry = string(D.SensorGeometry);
D.Algorithm = string(D.Algorithm);

%% Crossover summary
sumRows = cell(0,17);
for n = 1:numel(noiseOrder)
    for g = 1:numel(geomOrder)
        for m = 1:numel(testMethods)
            idx = D.NoiseModel==noiseOrder(n) & ...
                  D.SensorGeometry==geomOrder(g) & ...
                  D.Algorithm==testMethods(m);
            if ~any(idx), continue; end
            ds = D.DeltaSSIM_vs_DAS(idx);
            dp = D.DeltaPSNR_dB_vs_DAS(idx);
            dd = D.DeltaDice_vs_DAS(idx);
            sumRows(end+1,:) = {noiseOrder(n),geomOrder(g),testMethods(m), ...
                nnz(idx), ...
                mean(ds,'omitnan'),median(ds,'omitnan'),min(ds),max(ds),sum(ds>0), ...
                mean(dp,'omitnan'),median(dp,'omitnan'),min(dp),max(dp),sum(dp>0), ...
                mean(dd,'omitnan'),min(dd),max(dd)}; %#ok<AGROW>
        end
    end
end

S = cell2table(sumRows,'VariableNames', ...
    {'NoiseModel','SensorGeometry','Algorithm','NumPhantoms', ...
     'MeanDeltaSSIM','MedianDeltaSSIM','MinDeltaSSIM','MaxDeltaSSIM', ...
     'NumPhantoms_SSIM_Above_DAS', ...
     'MeanDeltaPSNR_dB','MedianDeltaPSNR_dB','MinDeltaPSNR_dB','MaxDeltaPSNR_dB', ...
     'NumPhantoms_PSNR_Above_DAS', ...
     'MeanDeltaDice','MinDeltaDice','MaxDeltaDice'});
S.NoiseModel = string(S.NoiseModel);
S.SensorGeometry = string(S.SensorGeometry);
S.Algorithm = string(S.Algorithm);
writetable(S,fullfile(outputDir,'noise_robustness_crossover_summary.csv'));

%% Figure: explicit phantom-level values + descriptive mean/min-max
fig = figure('Color','w','Position',[60 40 1750 1050]);
tl = tiledlayout(fig,2,2,'TileSpacing','compact','Padding','compact');

makeDeltaPanel(nexttile(tl,1),D,noiseOrder,noiseLabels, ...
    "CIRCULAR_FULL","DeltaSSIM_vs_DAS",testMethods, ...
    "(a) Full view: \DeltaSSIM relative to DAS","\DeltaSSIM");
makeDeltaPanel(nexttile(tl,2),D,noiseOrder,noiseLabels, ...
    "CIRCULAR_FULL","DeltaPSNR_dB_vs_DAS",testMethods, ...
    "(b) Full view: \DeltaPSNR relative to DAS","\DeltaPSNR [dB]");
makeDeltaPanel(nexttile(tl,3),D,noiseOrder,noiseLabels, ...
    "LIMITED_VIEW_ARC","DeltaSSIM_vs_DAS",testMethods, ...
    "(c) Limited view: \DeltaSSIM relative to DAS","\DeltaSSIM");
makeDeltaPanel(nexttile(tl,4),D,noiseOrder,noiseLabels, ...
    "LIMITED_VIEW_ARC","DeltaPSNR_dB_vs_DAS",testMethods, ...
    "(d) Limited view: \DeltaPSNR relative to DAS","\DeltaPSNR [dB]");

title(tl, ...
    "Noise-model sensitivity of the -5 dB DMAS/DASDSF crossover", ...
    'FontWeight','bold','FontSize',18);

pngFile = fullfile(outputDir,'Figure_noise_model_robustness.png');
pdfFile = fullfile(outputDir,'Figure_noise_model_robustness.pdf');
exportgraphics(fig,pngFile,'Resolution',300);
exportgraphics(fig,pdfFile,'ContentType','vector');
close(fig);

%% Console interpretation helper
fprintf('\n===============================================================\n');
fprintf('noise robustness: descriptive phantom-level summary\n');
fprintf('===============================================================\n');
for g = 1:numel(geomOrder)
    fprintf('\n%s\n',geomLabels(g));
    for n = 1:numel(noiseOrder)
        fprintf('  %-28s',noiseLabels(n));
        for m = 1:numel(testMethods)
            idx = S.NoiseModel==noiseOrder(n) & ...
                  S.SensorGeometry==geomOrder(g) & ...
                  S.Algorithm==testMethods(m);
            if any(idx)
                fprintf(' | %s: dSSIM=%+.4f (%d/%d > DAS), dPSNR=%+.3f dB', ...
                    testMethods(m),S.MeanDeltaSSIM(idx), ...
                    S.NumPhantoms_SSIM_Above_DAS(idx),S.NumPhantoms(idx), ...
                    S.MeanDeltaPSNR_dB(idx));
            end
        end
        fprintf('\n');
    end
end

outputs = struct();
outputs.phantomLevel = P;
outputs.absoluteSummary = A;
outputs.deltaByPhantom = D;
outputs.crossoverSummary = S;
outputs.figurePNG = string(pngFile);
outputs.figurePDF = string(pdfFile);
outputs.outputDir = string(outputDir);
end

% =========================================================================
function makeDeltaPanel(ax,D,noiseOrder,noiseLabels,geometry,metric,methods,ttl,ylab)
hold(ax,'on'); box(ax,'on'); grid(ax,'on');
yline(ax,0,'--','DAS reference','LabelHorizontalAlignment','left', ...
    'HandleVisibility','off');

x = 1:numel(noiseOrder);
offsets = [-0.12 0.12];
markers = {'o','s'};

for m = 1:numel(methods)
    means = nan(size(x));
    lows = nan(size(x));
    highs = nan(size(x));

    for n = 1:numel(noiseOrder)
        idx = D.SensorGeometry==geometry & ...
              D.NoiseModel==noiseOrder(n) & ...
              D.Algorithm==methods(m);
        vals = D.(metric)(idx);
        if isempty(vals), continue; end
        means(n) = mean(vals,'omitnan');
        lows(n) = means(n)-min(vals);
        highs(n) = max(vals)-means(n);

        % Plot each phantom explicitly.
        xx = x(n)+offsets(m) + linspace(-0.025,0.025,numel(vals));
        scatter(ax,xx,vals,30,'filled','MarkerFaceAlpha',0.65, ...
            'HandleVisibility','off');
    end

    errorbar(ax,x+offsets(m),means,lows,highs, ...
        'LineWidth',1.4,'Marker',markers{m},'MarkerSize',7, ...
        'DisplayName',methods(m));
end

xlim(ax,[0.5 numel(noiseOrder)+0.5]);
xticks(ax,x);
xticklabels(ax,noiseLabels);
xtickangle(ax,18);
ylabel(ax,ylab);
title(ax,ttl,'FontWeight','bold');
legend(ax,'Location','best','Box','off');
set(ax,'FontName','Times New Roman','FontSize',11,'LineWidth',0.9);
end
